
version: "3"
services:
  
  ui:
   build:
      context: ./ui
      dockerfile: Dockerfile.dev
   ports:
    -  4200:4200
   container_name: web-ui
   
   volumes:
    -  ./ui/src:/usr/app/src
    -  ./ui/public:/usr/app/public
   depends_on:
    - api
   stdin_open: true
   tty: true